version: '3.8'

services:
  php:
    image: php:8.3-apache
    container_name: projet-react_api
    ports:
      - "8005:80"  # Accès à l'application PHP via localhost:8005
    volumes:
      - ./api:/var/www/html  # Montre le dossier `api` dans le conteneur
    # Tu n'as pas besoin de `build:` si tu utilises une image PHP existante
    depends_on:
      - db  # S'assurer que le service `php` démarre après `db`

  db:
    image: mysql:8.0
    container_name: projet-react-api-php-db  # Nom unique du conteneur pour éviter les conflits
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet_api_react
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # Scripts d'initialisation de la base de données
    ports:
      - "3315:3306"  # Accès à MySQL via localhost:3315

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: projet_react-api-php_pma  # Nom unique pour éviter les conflits
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 20M
    ports:
      - "8085:80"  # Accès à phpMyAdmin via localhost:8085
    depends_on:
      - db  # Assure que phpMyAdmin démarre après la base de données
